---
collections:
  - name: infra.controller_configuration
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
  - name: kubealex.eda
    source: https://galaxy.ansible.com
